optionタグをhtml文字列で表記
chihiro-kakizaki/todolist pull request #3
Opened 2022-07-27 01:25 UTC by chihiro-kakizaki

2022-07-27 01:43 UTC, Shibata0806 commented on chihiro_todo/main.js
> +const addTask = function(newTask, selectPerson) {
@chihiro-kakizaki 
`選択された担当者ID`という意味で`selectedPersonId`と命名してあげた方が適切かと思いました！
```suggestion
const addTask = function(newTask, selectedPersonId) {
```

2022-07-27 09:55 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +const addTask = function(newTask, selectPerson) {
引数名の変更及び、renderSelectPersonBox関数内においてvalueの戻り値が不要だったため、iを削除しました。

2022-07-27 10:10 UTC, Shibata0806 commented on chihiro_todo/main.js
> +const addTask = function(newTask, selectPerson) {
@chihiro-kakizaki 
ありがとう！
こんな感じで対応したことを箇条書きにすると、より見やすいと思います！

例: ======
以下のコミットで3点対応いたしました。
https://github.com/chihiro-kakizaki/todolist/pull/3/commits/cab86679c173a53c226560867027e1c1bde11dd4
- `selectPerson`という変数名を`selectedPersonId`に修正
- `renderSelectPersonBox`関数内の`map`関数の引数の`index`は不要だったため削除
- `querySelector`で`select`要素を取得する箇所を1箇所に集約
======
上の3つをそれぞれ別のコミットに分けてあげてもよかったかもね！

Githubのマークダウンの記法についても、知っておいた方が、より見やすい記述をできるから、積極的に使っていくようにしよう！
https://gist.github.com/mignonstyle/083c9e1651d7734f84c99b8cf49d57fa

2022-07-27 10:29 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +const addTask = function(newTask, selectPerson) {
ご指摘ありがとうございます🙇
今後は修正点をコミットごとに分けて対応するように気をつけます。
また、マークダウン記法も意識して使うようにしたいと思います！！

2022-07-27 10:51 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +const addTask = function(newTask, selectPerson) {
担当者の追加機能についても作成しましたので併せてご確認お願い致します🙇‍♀️

2022-07-27 11:02 UTC, Shibata0806 commented on chihiro_todo/main.js
> +    const newPersonId = new Date().getTime().toString();
@chihiro-kakizaki 
ここのIDを発行する部分は`addPerson`関数内に移動して、`addPerson`内で発行する形にした方が良さそうだね！

2022-07-27 11:05 UTC, Shibata0806 commented on chihiro_todo/main.js
> +const addPerson = function(newPersonId, newPersonName) {
@chihiro-kakizaki 
何も入力されてなかったら処理終了させないと、空文字で担当者が追加されてしまうので、`addTask`関数に倣って、returnで処理終了させるようにしてください！

2022-07-27 11:33 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +const addPerson = function(newPersonId, newPersonName) {
確かに、担当者名が空欄だった場合の処理を追加していませんでした💦
ご指摘ありがとうございます。
以下のコミットで2点対応致しました。
- newPersonIdをaddPerson関数内で直接発行に修正し、newPersonIdの変数を削除
- addPerson関数内でnewPersonNameが空欄だった場合に処理終了するような条件分岐を追加

よろしくお願い致します🙇‍♀️

2022-07-27 11:36 UTC, Shibata0806 commented on chihiro_todo/main.js
> +const addPerson = function(newPersonId, newPersonName) {
@chihiro-kakizaki 
ありがとうございます！！
いい感じですね！！

2022-07-27 12:01 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +const addPerson = function(newPersonId, newPersonName) {
確認していただきありがとうございます！
以下2点の機能を作成しました。
- 担当者の一覧表示機能
- 担当者の削除機能
　
よろしくお願い致します🙇‍♀️

2022-07-28 08:30 UTC, Shibata0806 commented on chihiro_todo/main.js
>  });
@chihiro-kakizaki 
今思ったけど、このファイルの一番上から一番下まで、DOMの読み込み後に実行するものだから、全部を`document.addEventListener('DOMContentLoaded', function() {}`で囲んであげた方が良いと思いました！

2022-07-31 10:37 UTC, chihiro-kakizaki commented
以下の2点を修正しました。

- 担当者機能について追加致しました。
- html文字列での記述からcreateElementへの記述へ変更

ご確認よろしくお願い致します🙇‍♀️

2022-07-31 23:07 UTC, chihiro-kakizaki commented
併せて以下の2点をコミットしました。
- 担当者一覧リストに削除ボタンを生成し、セレクトボックス にも連動して削除する機能
- 各todoリスト横に担当者名を表示する機能

ご確認よろしくお願い致します🙇‍♀️

2022-08-01 01:01 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        deleteTargetElm = document.querySelector('#task_' + taskId);
@chihiro-kakizaki 
ここは`const`をつけてあげましょう！
全体的に`document.querySelector`でDOMを取得してるところが`const`が漏れがちみたいなので、確認お願いします！

2022-08-01 01:03 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        taskPersonElm.textContent = person.name;
@chihiro-kakizaki 
person関連の要素を作成しているソースと`<li>`の要素を作ってidを付与する処理が混ざっているようです。person関連の処理は116行目あたりの`appendChild`の直前に移動させて、見通しを良くしましょうか！

```
 const person = personList.find(person => person.id === task.personId);
taskPersonElm = document.createElement('span');
taskPersonElm.textContent = person.name;
```

2022-08-01 01:07 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        personListArea.removeChild(deletePersonElm);
@chihiro-kakizaki 
このif分は170行目でtaskをfindした直後にあった方が良いですね！

2022-08-01 01:12 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        });
@chihiro-kakizaki 
この`forEach`の中で`selectPersonBox`メソッドを使ってあげると処理をまとめられそうです。
```suggestion
        personList.forEach((person) => {
            selectPersonBox(person);
        });
```

2022-08-01 01:13 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        });
@chihiro-kakizaki 
この`forEach`の中で`appendPerson`を呼んであげたら、処理をまとめられそうです！
```suggestion
        personList.forEach((person) => {
            appendPerson(person);
        });
```

2022-08-01 01:14 UTC, Shibata0806 commented on chihiro_todo/main.js
> +    const defaultPerson = function() {
@chihiro-kakizaki 
このメソッド名だと、`デフォルトの担当者`という意味になってしますので、`デフォルトの担当者を表示`という意味にできるように、`appendDefaultPerson`という名前にした方がよさそうです！

2022-08-01 01:16 UTC, Shibata0806 commented on chihiro_todo/main.js
> +    const selectPersonBox = (person) => {
@chihiro-kakizaki 
このメソッド名だと`担当者のボックスを選択する`という意味になってしまうので、`担当者のセレクトボックスを表示する`という意味になるように、`appendPersonSelectBox`とするのがよさそうですね！

2022-08-01 01:17 UTC, Shibata0806 commented on chihiro_todo/main.js
> +    const defaultSelectPersonBox = () => {
@chihiro-kakizaki 
これも同じく、`デフォルトの担当者のセレクトボックスを表示する`という意味で、`appendDefaultPersonSelectBox`というメソッド名にするのがよさそうです！

2022-08-01 11:45 UTC, chihiro-kakizaki commented
細部までご確認いただきありがとうございます🙇‍♀️
以下7点のコミットで修正致しました。

- document.querySelectorでDOMを取得した部分をconst変数に格納
- appendTask関数内のpersonに関連する処理を末尾での記述に変更
- deletePerson内のif文の位置をtask変数の直後に変更
- defaultSelectPersonBox関数内の処理の記述をselectPersonBox関数を用いて省略し、selectPersonBox関数内のoption要素名をappendPersonSelectElmに変更
- defaultPerson関数内の処理の記述をappendPerson関数を用いて省略し、appendPerson関数内のli要素名をappendPersonElmに変更
- defaultPersonメソッドをappendDefaultPersonに名称変更
- selectPersonBoxメソッドをappendPersonSelectBoxに名称変更、defaultSelectPersonBoxメソッドをappendDefaultSelectPersonBoxに名称変更

メソッド名や共通処理など、今後は意識してコーディングしていきたいと思います💦
ご確認よろしくお願い致します。

2022-08-02 00:48 UTC, Shibata0806 requested changes
@chihiro-kakizaki 
ごめん！まだ気になるところがあったので、コメントしました！！
主に以下です！！
- constがまだ足りてないところがある
- 変数名がちょっと気になった

2022-08-02 00:48 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        newTaskElm = document.createElement('li');
@chihiro-kakizaki 
ここもconstが必要です！！

2022-08-02 00:48 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        taskPersonElm = document.createElement('span');
@chihiro-kakizaki 
ここもconstが必要です！！

2022-08-02 00:48 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        appendPersonElm = document.createElement('li');
@chihiro-kakizaki 
ここもconstが必要です！！

2022-08-02 00:48 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        deleteButton = document.createElement('button');
@chihiro-kakizaki 
ここもconstが必要です！！

2022-08-02 00:48 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        appendPersonSelectElm = document.createElement('option');
@chihiro-kakizaki 
ここもconstが必要です！！

2022-08-02 00:48 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        appendPersonSelectElm = document.createElement('option');
@chihiro-kakizaki 
あ、あと、ここの変数名は`新しい担当者のselectの要素`ってことで`newPersonSelectElm`とかで良いと思う！

変数名の命名については、`形容詞+名詞`を意識するといいみたいね！
以下のブログが参考になりそうかな！
https://note.zochang.com/n/n792ba66f7908

例えば、変数名にどうしても`append`を使いたいときは`appended`にして使うと良いみたいね！！

ついでに`append`とか`render`とかの意味を改めて調べてみたら、
`append` -> `追加する`
`render` -> `描画する`
という意味だったから、
要素を追加するとかの文脈だと`append`を使って、
htmlを描画するっていう文脈だと`render`を使うのがよさそうね！判断むずい時ありそうだけど、、、笑

2022-08-02 00:50 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        newTaskElm = document.createElement('li');
ちなみに、constをつけないと、グローバル変数になってしまって、それなりに規模が大きくなってきた時に結構危険なバグを生んでしまうこともあるので、気をつけましょう！！
https://kenju.gitbooks.io/js_step-up-to-intermediate/content/content/part01/avoid_abusing_global_variables.html

2022-08-02 01:17 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +        appendPersonSelectElm = document.createElement('option');
詳しい説明や参考リンクをありがとうございます🙇‍♀️
今後、変数名を決める際には参考にさせていただきます！

以下のコミットで2点修正しました。
- 各変数名にconstを付与しグローバル変数に変更
- appendPersonSelectElmを新たな担当者のセレクト要素という意味に倣いnewPersonSelectElmに要素名を変更

ご確認よろしくお願い致します。

2022-08-02 01:22 UTC, Shibata0806 approved these changes
LGTM!

2022-08-02 01:57 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        taskPersonElm = document.createElement('span');
@Shibata0806 
こちらで修正しました！
[各変数にconstを追加](https://github.com/chihiro-kakizaki/todolist/pull/3/commits/b1a17118df39e6e97c0979908e5198d51fd6e126)

2022-08-02 05:45 UTC, merged