css追加
chihiro-kakizaki/todolist pull request #4
Opened 2022-08-03 02:38 UTC by chihiro-kakizaki

2022-08-04 02:22 UTC, Shibata0806 requested changes
@chihiro-kakizaki 
おおむねいい感じだと思います！

marginとpaddingを使ってのレイアウト調整はちょっと感覚的に難しいところあると思うけど頑張って掴みましょう！
https://eclair.blog/difference-between-margin-and-padding/#:~:text=%E5%9F%BA%E6%9C%AC%E3%81%AF%E3%80%81%E8%A6%81%E7%B4%A0%E3%81%AE%E5%A4%96%E5%81%B4,%E8%BF%B7%E3%81%86%E3%81%93%E3%81%A8%E3%81%8C%E3%81%AA%E3%81%8F%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82

↑これが参考になりそうでした！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    word-break: break-all;
@chihiro-kakizaki 
<img width="494" alt="image" src="https://user-images.githubusercontent.com/51699053/182746783-07481f5f-a7e4-436c-a858-12bdc53ff846.png">
か改行した時にbottonも高さが大きくなってしまうので、最大の高さを固定して、見た目が変にならないようにしましょう！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/todo.html
> +                        <h2>Todo Tasks</h2>
<img width="445" alt="image" src="https://user-images.githubusercontent.com/51699053/182747007-c76f1176-da19-4894-95c2-6ff1ff9d960d.png">
h2タグの要素がすべてくっついてしまっているので、あらかじめ高さを持たせるようにしたいですね！

あと、タスクが表示される部分の背景がスプレッドシートではグレーになっているので、そのような見た目にしましょう！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    padding-bottom: 20px;
@chihiro-kakizaki 
ここは他の要素との間隔を空けたいという意図で使っているのであれば、`margin-bottom`を使った方がよさそうに思います。

paddingをつけると、アンダーライン（border-botom）をつけたくなったときに、文字からpadding幅分が空いた状態になってしまったりしまいます。

ざっくりですが、
marginは他の要素との間隔を空けたい時
paddingは自分自身の中で間隔を空けたい時
みたいなイメージですかね！

他にも同じような意図でpaddingを使ってるところは修正お願いします！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    padding-bottom: 20px;
あ、ここのh1に限った話で言うと、h1にmargin持たせるより、headerタグにpadding持たせて幅取ってあげる方が、正しい気がします！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    padding: 10px 0;
@chihiro-kakizaki 
ここも、h2に直接paddingやmarginをつけるよりも、
sectionやformにpaddingをつけてレイアウトしてあげる方が綺麗に思います！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    padding-bottom: 20px;
考え方としては、wrapperクラスにpadding持たせてるのと近いですね！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        console.log(appendPersonNameElm)
@chihiro-kakizaki 
debugに使ったconsole.logの残骸は削除しておきましょう！

2022-08-04 02:22 UTC, Shibata0806 commented on chihiro_todo/todo.html
> +                    <h2>担当管理者</h2>
@chihiro-kakizaki 
スペルミスみたいなのありました！
```suggestion
                    <h2>担当者管理</h2>
```

2022-08-04 05:33 UTC, chihiro-kakizaki commented on chihiro_todo/main.css
> +    word-break: break-all;
@Shibata0806 
以下のコミットで修正致しました🙇‍♀️
[buttonにmax-heightを設定しボタンの大きさが変化しないように設定](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/7717c72a86bfc6342575a99928542d9f9b21a72a)

2022-08-04 05:34 UTC, chihiro-kakizaki commented on chihiro_todo/todo.html
> +                        <h2>Todo Tasks</h2>
@Shibata0806 
以下のコミットで修正致しました。
[todo,doing,done表示一覧部分にmin-heightを設定しデフォルトで高さを持たせ、背景色をグレーに設定](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/1442145bbbea2913975e113615f6e2e6bbdc0ad9)

2022-08-04 05:36 UTC, chihiro-kakizaki commented on chihiro_todo/main.css
> +    padding-bottom: 20px;
以下のコミットで修正致しました。
[各要素のmargin,padding設定を修正](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/4066173018e98818f3de0d2d1a28b7789d652bdb)

2022-08-04 05:36 UTC, chihiro-kakizaki commented on chihiro_todo/main.css
> +    padding: 10px 0;
以下のコミットで修正致しました。
[各要素のmargin,padding設定を修正](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/4066173018e98818f3de0d2d1a28b7789d652bdb)

margin,paddingの使い方でまた誤りがありましたら、ご指摘頂けますと幸いです🙇‍♀️

2022-08-04 05:38 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +        console.log(appendPersonNameElm)
@Shibata0806 
console.logを削除し忘れていました、すみません🙇‍♀️💦
以下のコミットで修正致しました。
[console.logを削除](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/8cddea53373eb183d1b66b902b261dab38bb7a7d)

2022-08-04 05:39 UTC, chihiro-kakizaki commented on chihiro_todo/todo.html
> +                    <h2>担当管理者</h2>
@Shibata0806 
スペルミスについても以下のコミットにて修正致しました。
[h2の担当管理者を担当者管理に修正](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/0b71e93374442b32184d4849c7f1e49638a65f13)

2022-08-04 05:56 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    word-break: break-all;
@chihiro-kakizaki 
```
.task_list > li > div, button, span, .person_list > li > div, button {
```
ここのbuttonはクラス名ついてるから、`.button`でもいいかも！
あと、できれば、buttonには`word-break: break-all;`はつかないでいいのだろうけど！って思いました！

あと、英語と日本語でボタンの高さが変わってしまってるみたい💦
<img width="489" alt="image" src="https://user-images.githubusercontent.com/51699053/182773365-25e90f2e-3427-4340-b5a7-c50a4605886a.png">

2022-08-04 06:10 UTC, Shibata0806 commented on chihiro_todo/todo.html
> +                        <h2>Todo Tasks</h2>
@chihiro-kakizaki 
修正ありがとうございます！
このままだと不恰好だから、marginとpaddingで余白を持たせたり、グレーの背景の四隅を角丸にしたりしてみてください！

あと、せっかくだから、inputとかselectももう少し自前のスタイルが当たってる方がかっこいいかなと思ったので、ちょっとやってみてください！！

例えば、以下のような感じです！
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/51699053/182775388-decb07f4-1c8b-475d-acdf-457408621748.png">

2022-08-04 06:12 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    padding: 10px 0;
@chihiro-kakizaki 
ありがとうございます！いいと思います！

2022-08-04 06:14 UTC, Shibata0806 commented on chihiro_todo/main.css
> +    word-break: break-all;
これは、次のコメントの指摘と合わせて対応してしまって大丈夫です！

2022-08-05 07:23 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        const personNameBeforeChengeElm = beforeChangeElm.querySelector('div');
@chihiro-kakizaki 
[nits]
```suggestion
        const personNameBeforeChangeElm = beforeChangeElm.querySelector('div');
```
ここが綴り間違ってるみたいですね！

2022-08-05 07:23 UTC, Shibata0806 commented on chihiro_todo/main.js
> +        console.log(changedPersonElm)
[nits]
このconsole.log消しちゃいましょう！

2022-08-05 07:30 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +        const personNameBeforeChengeElm = beforeChangeElm.querySelector('div');
@Shibata0806
気付きませんでした💦
ご指摘ありがとうございます🙇‍♀️
以下のコミットにて修正しました。
[personNameBeforeChangeElmのスペルミス修正](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/3f87c479882b9ab8dc5c732b44327cfda0a30006)

2022-08-05 07:30 UTC, chihiro-kakizaki commented on chihiro_todo/main.js
> +        console.log(changedPersonElm)
@Shibata0806 
以下のコミットにて修正致しました。
[console.log削除](https://github.com/chihiro-kakizaki/todolist/pull/4/commits/343f90bbcccf7e0828bb2753ffde2c9422e73479)

2022-08-05 07:36 UTC, Shibata0806 approved these changes
LGTM!!

2022-08-05 07:38 UTC, merged