jqueryでtodolist作成
chihiro-kakizaki/todolist pull request #5
Opened 2022-08-10 05:05 UTC by chihiro-kakizaki

2022-08-10 08:00 UTC, Shibata0806 requested changes
@chihiro-kakizaki 
遅くなりましたが、一通りレビューしました！
やっぱり、変数名とメソッド名の命名だったりとか、ソースの切り出す判断とかがまだまだ経験が必要そうだね！！
いくつかコメントで残してますが、全体的に見直しましょう！

あと、メソッドチェーンを使いこなすと、わざわざ変数に定義してあげる必要がなくなって、変数名を考える辛さから解放されそうだなって思った！ソースの見通しが悪くならないかを意識しながらチャレンジしてみてください！

あと、一部仕様が足りてない部分があったので、コメント残しておきました！！

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +        const createValue = new Date().getTime().toString()
@chihiro-kakizaki 
`createValue`だと、`値を作る`っていうメソッド名みたいに見えてしまうので、変数名にするなら`createdValue`かな！
ただ、`作られた値`っていうのも抽象的すぎるから、素直に、`peresonId`で良いのではないかと思います！
```suggestion
        const personId = new Date().getTime().toString()
```

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    deletePersonButton(personElm);
@chihiro-kakizaki 
この二つのメソッドは、ここでしか使ってないから、わざわざ切り出さない方が良いと思いました！（見通しが悪くなってしまうので）
あと、命名はつけるとしたら`appendEditPersonButton`かな！
`editPersonButton`だと、`担当者ボタンを編集する`という意味のメソッドになってしまいます。

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    $('#person_name').val("");
@chihiro-kakizaki 
inputタグを空にするのはここでやらないほうが良さそうです。
`appendPerson()`自体を呼んでる処理を見ると、必ずしも`input#person_name`の値を見ている訳ではなさそうなので、バグに繋がりそうです。
例えば、担当者新規追加のinputに文字を入力した状態で、edit->saveをすると、inputに入力中だった文字が消えてしまいます。

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +function appendNewSelectPerson(personName, createValue) {
@chihiro-kakizaki 
このメソッドも一箇所からしか呼ばれていないので、切り出す必要がなさそうです！

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +function deletePerson() {
@chihiro-kakizaki 
担当者が、タスクに紐づいていた場合にアラートを出す仕様が足りていないようです！！

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +            }
@chihiro-kakizaki 
この辺のインデントが変になってそうですね！

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    const beforeChangedeleteButton = personElm.children().last();
@chihiro-kakizaki 
変数名が一部キャメルケースになってないですね！
```suggestion
    const beforeChangeDeleteButton = personElm.children().last();
```

2022-08-10 08:00 UTC, Shibata0806 commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    editPersonInput.replaceAll(beforeChangePersonElm)
@chihiro-kakizaki 
全体的に、こんな感じでメソッドチェーンで書いてあげると、変数名考える地獄から解放されるかも！！笑
```suggestion
     $('<input>').attr('id', 'edit_input')
        .val(beforeEditPersonName)
        .replaceAll(beforeChangePersonElm);
```

2022-08-11 06:46 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +        const createValue = new Date().getTime().toString()
@Shibata0806 
変数名がわかりづらいですね、、ご指摘ありがとうございます🙇‍♀️
以下のコミットにて修正しました。
[変数名createValueをpersonIdに変更](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/c19140eb7aa173e147475dd1f58818a6281edf1e)

2022-08-11 06:47 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    deletePersonButton(personElm);
@Shibata0806 
以下のコミットで修正しました。
[editButton,deleteButtonの切り出しをやめ、appendPerson内に記述](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/d42be502724f63f94ae8973ac64cff91c27923e3)

2022-08-11 06:47 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    $('#person_name').val("");
@Shibata0806 
以下のコミットで修正致しました。
[$(#person_name).val("");の記述を削除](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/f822867e1e097bbb58f478f886c530eb17a4e994)

2022-08-11 06:48 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +function appendNewSelectPerson(personName, createValue) {
@Shibata0806 
以下のコミットで修正しました。
[appendNewSelectPersonの切り出しをやめ、 $(#person_submit).click関数内に記述](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/cf3e8a556e5e46f3d21028399eb3bdd19203037e)

2022-08-11 06:49 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +function deletePerson() {
@Shibata0806 
機能をつけ忘れてしまいました💦
以下のコミットにて機能追加しました。
[担当者にtaskが紐づいている場合にalertが出るように設定](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/764c1181cc90e6ecb9b6c38431dae3ebcf702c8f)

2022-08-11 06:50 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +            }
@Shibata0806 
以下のコミットにてインデントを修正しました。
[インデント修正](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/bfe9d2bc5fe2a35577cd759abec1304b98eb7328)

2022-08-11 06:50 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    const beforeChangedeleteButton = personElm.children().last();
@Shibata0806 
以下のコミットにて修正しました。
[キャメルケースに修正](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/005c2c333caea30970e8c392ba5a45965110dda1)

2022-08-11 06:52 UTC, chihiro-kakizaki commented on chihiro_todo/chihiro_jquery_todo/jquery.js
> +    editPersonInput.replaceAll(beforeChangePersonElm)
@Shibata0806 
メソッドチェーンを使うことで変数名の定義が要らなくなるのですね！
以下のコミットで修正しました。
[メソッドチェーンに修正](https://github.com/chihiro-kakizaki/todolist/pull/5/commits/dc5fb466c6bfbae2a295bcea9120afeb28796a64)

各ボタンについてはメソッドチェーンを使うか迷いましたが、コードの解読が難しくなるかなと考え、メソッドチェーンを使わずにそのまま記述しています。
気になる点がありましたらご指摘頂けると幸いです🙇‍♀️

2022-08-14 01:34 UTC, Shibata0806 approved these changes

2022-08-14 01:35 UTC, merged